//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinBascula
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class industriaEntities : DbContext
    {
        public industriaEntities()
            : base("name=industriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_bas_personas> tbl_bas_personas { get; set; }
        public virtual DbSet<tbl_bas_articulos> tbl_bas_articulos { get; set; }
        public virtual DbSet<tbl_bas_pesadas> tbl_bas_pesadas { get; set; }
    }
}
