//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinBascula
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class tbl_bas_articulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_bas_articulos()
        {
            this.tbl_bas_pesadas = new ObservableCollection<tbl_bas_pesadas>();
        }
    
        public int id { get; set; }
        public string codigo_oracle { get; set; }
        public string descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<tbl_bas_pesadas> tbl_bas_pesadas { get; set; }
    }
}
