//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinBascula
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class tbl_bas_personas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_bas_personas()
        {
            this.tbl_bas_pesadas = new ObservableCollection<tbl_bas_pesadas>();
            this.tbl_bas_pesadas1 = new ObservableCollection<tbl_bas_pesadas>();
        }
    
        public int id { get; set; }
        public string razon_social { get; set; }
        public string rucci { get; set; }
        public int ctacte { get; set; }
        public Nullable<int> id_tblempresas { get; set; }
        public string observacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<tbl_bas_pesadas> tbl_bas_pesadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<tbl_bas_pesadas> tbl_bas_pesadas1 { get; set; }
    }
}
