//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinBascula
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class tbl_bas_pesadas
    {
        public int id { get; set; }
        public System.DateTime fechahora_entrada { get; set; }
        public System.DateTime fechahora_salida { get; set; }
        public string chapa { get; set; }
        public int id_propietario { get; set; }
        public int id_transportista { get; set; }
        public int id_articulo { get; set; }
        public int peso_bruto { get; set; }
        public int peso_tara { get; set; }
        public bool descarga_autorizada { get; set; }
        public bool enviado_opm { get; set; }
        public Nullable<int> id_lote { get; set; }
        public bool anulado { get; set; }
    
        public virtual tbl_bas_articulos tbl_bas_articulos { get; set; }
        public virtual tbl_bas_personas tbl_bas_personas { get; set; }
        public virtual tbl_bas_personas tbl_bas_personas1 { get; set; }
    }
}
